version: '3.1'

services:
  restic:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./my-backups:/backups
      - ./my-data:/data:ro
    environment:
      RESTIC_PASSWORD: Correct.Horse.Battery.Staple Plus
      CRON_SCHEDULE: "* * * * *"
      VERIFY_CRON_SCHEDULE: "* * * * *"
